version: '3'

services:


  inali-mapa-interactivo:
    container_name: inali-mapa-interactivo
    build: 
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./:/src/inali-mapa-interactivo
    environment:
      VIRTUAL_HOST: inali-mapa-interactivo.ccdadc.dev 
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: inali-mapa-interactivo.ccdadc.dev
      LETSENCRYPT_EMAIL: furenku@gmail.com
networks:
  default:
    external:
      name: nginx-proxy