export default [
    {
        id: 1,
        nombreOriginario: "Kickapoo",
        nombreCastellanizado: "",
        otrosNombres: "",
        transcripcionFonetica: "",
        comunidadesHablantes: "",
        alfabeto: "",
        coordenadas: {
            latitud: "",
            longitud: "",
        },
        categoriasLinguisticas: "",
        riesgoDesaparicion: "0.15",
        datosEstadisticos: {
            cantidadHablantes: 11.111,
            distribucionDemografica: "",
        },
        audios: "",
        fotografias: "",
        textiles: "",
        twitterCuentas: "",
        twitterHashtags: "",
        tweets: "",
        normaDeEscritura: "",
        variantes: [1,2,3,4],
    },
    {
        id: 2,
        nombreOriginario: "Pápago",
        nombreCastellanizado: "",
        otrosNombres: "",
        transcripcionFonetica: "",
        comunidadesHablantes: "",
        alfabeto: "",
        coordenadas: {
            latitud: "",
            longitud: "",
        },
        categoriasLinguisticas: "",
        riesgoDesaparicion: "0.85",
        datosEstadisticos: {
            cantidadHablantes: 4.328,
            distribucionDemografica: "",
        },
        audios: "",
        fotografias: "",
        textiles: "",
        twitterCuentas: "",
        twitterHashtags: "",
        tweets: "",
        normaDeEscritura: "",
        variantes: [1,2,3,4],
    },
    {
        id: 3,
        nombreOriginario: "paipai",
        nombreCastellanizado: "",
        otrosNombres: "",
        transcripcionFonetica: "",
        comunidadesHablantes: "",
        alfabeto: "",
        coordenadas: {
            latitud: "",
            longitud: "",
        },
        categoriasLinguisticas: "",
        riesgoDesaparicion: "0.49",
        datosEstadisticos: {
            cantidadHablantes: 18.018,
            distribucionDemografica: "",
        },
        audios: "",
        fotografias: "",
        textiles: "",
        twitterCuentas: "",
        twitterHashtags: "",
        tweets: "",
        normaDeEscritura: "",
        variantes: [1,2,3,4],
    },
    {
        id: 4,
        nombreOriginario: "otomí",
        nombreCastellanizado: "",
        otrosNombres: "",
        transcripcionFonetica: "",
        comunidadesHablantes: "",
        alfabeto: "",
        coordenadas: {
            latitud: "",
            longitud: "",
        },
        categoriasLinguisticas: "",
        riesgoDesaparicion: "0.51",
        datosEstadisticos: {
            cantidadHablantes: 28.718,
            distribucionDemografica: "",
        },
        audios: "",
        fotografias: "",
        textiles: "",
        twitterCuentas: "",
        twitterHashtags: "",
        tweets: "",
        normaDeEscritura: "",
        variantes: [1,2,3],
    }
]