export default [
    {
        id: 1,
        extra: "Extra",
        variantes: [1,2,3,4],
        nombreOriginario: "",
        nombreCastellanizado: "",
        otrosNombres: "",
        transcripcionFonetica: "",
        comunidadesHablantes: "",
        alfabeto: "",
        coordenadas: {
            latitud: "",
            longitud: "",
        },
        categoriasLinguisticas: "",
        riesgoDesaparicion: "0.45",
        datosEstadisticos: {
            cantidadHablantes: "",
            distribucionDemografica: "",
        },
        audios: "",
        fotografias: "",
        textiles: "",
        twitterCuentas: "",
        twitterHashtags: "",
        tweets: "",
        normaDeEscritura: "",
    },
    {
        id: 2,
        nombreOriginario: "",
        nombreCastellanizado: "",
        otrosNombres: "",
        variantes: [
            1,2,3
        ],
        transcripcionFonetica: "",
        comunidadesHablantes: "",
        alfabeto: "",
        coordenadas: {
            latitud: "",
            longitud: "",
        },
        categoriasLinguisticas: "",
        riesgoDesaparicion: "0.45",
        datosEstadisticos: {
            cantidadHablantes: "",
            distribucionDemografica: "",
        },
        audios: "",
        fotografias: "",
        textiles: "",
        twitterCuentas: "",
        twitterHashtags: "",
        tweets: "",
        normaDeEscritura: "",
    },
    {
        id: 3,
        nombreOriginario: "",
        nombreCastellanizado: "",
        otrosNombres: "",
        variantes: [
            1,2,3
        ],
        transcripcionFonetica: "",
        comunidadesHablantes: "",
        alfabeto: "",
        coordenadas: {
            latitud: "",
            longitud: "",
        },
        categoriasLinguisticas: "",
        riesgoDesaparicion: "0.45",
        datosEstadisticos: {
            cantidadHablantes: "",
            distribucionDemografica: "",
        },
        audios: "",
        fotografias: "",
        textiles: "",
        twitterCuentas: "",
        twitterHashtags: "",
        tweets: "",
        normaDeEscritura: "",
    },
    {
        id: 4,
        nombreOriginario: "",
        nombreCastellanizado: "",
        otrosNombres: "",
        variantes: [
            1,2,3
        ],
        transcripcionFonetica: "",
        comunidadesHablantes: "",
        alfabeto: "",
        coordenadas: {
            latitud: "",
            longitud: "",
        },
        categoriasLinguisticas: "",
        riesgoDesaparicion: "0.45",
        datosEstadisticos: {
            cantidadHablantes: "",
            distribucionDemografica: "",
        },
        audios: "",
        fotografias: "",
        textiles: "",
        twitterCuentas: "",
        twitterHashtags: "",
        tweets: "",
        normaDeEscritura: "",
    }
]