//version funcion
// import lenguasFake from "./lenguasFake";

// const generaFamilia = lenguasFake.generaFamilia
// generaFamilia('extra')

export default [
    {
        id: 1,
        nombreOriginario: "",
        agrupaciones: [1,2,3,4],
        nombreCastellanizado: "",
        otrosNombres: "",
        transcripcionFonetica: "",
        comunidadesHablantes: "",
        alfabeto: "",
        coordenadas: {
            latitud: "",
            longitud: "",
        },
        familia: [1,2,3,4],
        categoriasLinguisticas: "",
        riesgoDesaparicion: "0.45",
        datosEstadisticos: {
            cantidadHablantes: "",
            distribucionDemografica: "",
        },
        audios: "",
        fotografias: "",
        textiles: "",
        twitterCuentas: "",
        twitterHashtags: "",
        tweets: "",
        normaDeEscritura: "",
    },
    {
        id: 2,
        nombreOriginario: "",
        nombreCastellanizado: "",
        otrosNombres: "",
        agrupaciones: [1,2,3,4],
        transcripcionFonetica: "",
        comunidadesHablantes: "",
        alfabeto: "",
        coordenadas: {
            latitud: "",
            longitud: "",
        },
        familia: [1,2,3,4],
        categoriasLinguisticas: "",
        riesgoDesaparicion: "0.45",
        datosEstadisticos: {
            cantidadHablantes: "",
            distribucionDemografica: "",
        },
        audios: "",
        fotografias: "",
        textiles: "",
        twitterCuentas: "",
        twitterHashtags: "",
        tweets: "",
        normaDeEscritura: "",
    },
    {
        id: 3,
        nombreOriginario: "",
        nombreCastellanizado: "",
        otrosNombres: "",
        agrupaciones: [1,2,3,4],
        transcripcionFonetica: "",
        comunidadesHablantes: "",
        alfabeto: "",
        coordenadas: {
            latitud: "",
            longitud: "",
        },
        familia: [1,2,3,4],
        categoriasLinguisticas: "",
        riesgoDesaparicion: "0.45",
        datosEstadisticos: {
            cantidadHablantes: "",
            distribucionDemografica: "",
        },
        audios: "",
        fotografias: "",
        textiles: "",
        twitterCuentas: "",
        twitterHashtags: "",
        tweets: "",
        normaDeEscritura: "",
    },
    {
        id: 4,
        nombreOriginario: "",
        nombreCastellanizado: "",
        otrosNombres: "",
        agrupaciones: [1,2,3,4],
        transcripcionFonetica: "",
        comunidadesHablantes: "",
        alfabeto: "",
        coordenadas: {
            latitud: "",
            longitud: "",
        },
        familia: [1,2,3,4],
        categoriasLinguisticas: "",
        riesgoDesaparicion: "0.45",
        datosEstadisticos: {
            cantidadHablantes: "",
            distribucionDemografica: "",
        },
        audios: "",
        fotografias: "",
        textiles: "",
        twitterCuentas: "",
        twitterHashtags: "",
        tweets: "",
        normaDeEscritura: "",
    }
]