
export default [
    {
        id: 1,
        nombreOriginario: "Kickapoo",
        nombreCastellanizado: "",
        otrosNombres: "",
        transcripcionFonetica: "",
        comunidadesHablantes: "",
        alfabeto: "",
        coordenadas: {
            latitud: "",
            longitud: "",
        },
        categoriasLinguisticas: "",
        riesgoDesaparicion: "0.45",
        datosEstadisticos: {
            cantidadHablantes: "",
            distribucionDemografica: "",
        },
        audios: "",
        fotografias: "",
        textiles: "",
        twitterCuentas: "",
        twitterHashtags: "",
        tweets: "",
        normaDeEscritura: "",
    },
    {
        id: 2,
        nombreOriginario: "pápago",
        nombreCastellanizado: "",
        otrosNombres: "",
        transcripcionFonetica: "",
        comunidadesHablantes: "",
        alfabeto: "",
        coordenadas: {
            latitud: "",
            longitud: "",
        },
        categoriasLinguisticas: "",
        riesgoDesaparicion: "0.45",
        datosEstadisticos: {
            cantidadHablantes: "",
            distribucionDemografica: "",
        },
        audios: "",
        fotografias: "",
        textiles: "",
        twitterCuentas: "",
        twitterHashtags: "",
        tweets: "",
        normaDeEscritura: "",
    },
    {
        id: 3,
        nombreOriginario: "paipai",
        nombreCastellanizado: "",
        otrosNombres: "",
        transcripcionFonetica: "",
        comunidadesHablantes: "",
        alfabeto: "",
        coordenadas: {
            latitud: "",
            longitud: "",
        },
        categoriasLinguisticas: "",
        riesgoDesaparicion: "0.45",
        datosEstadisticos: {
            cantidadHablantes: "",
            distribucionDemografica: "",
        },
        audios: "",
        fotografias: "",
        textiles: "",
        twitterCuentas: "",
        twitterHashtags: "",
        tweets: "",
        normaDeEscritura: "",
    },
    {
        id: 4,
        nombreOriginario: "otomí de la Sierra ",
        nombreCastellanizado: "",
        otrosNombres: "",
        transcripcionFonetica: "",
        comunidadesHablantes: "",
        alfabeto: "",
        coordenadas: {
            latitud: "",
            longitud: "",
        },
        categoriasLinguisticas: "",
        riesgoDesaparicion: "0.45",
        datosEstadisticos: {
            cantidadHablantes: "",
            distribucionDemografica: "",
        },
        audios: "",
        fotografias: "",
        textiles: "",
        twitterCuentas: "",
        twitterHashtags: "",
        tweets: "",
        normaDeEscritura: "",
    }
]